apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxConfigMapName}}
data:
  nginx.conf: |
    worker_processes  3;
    pid /tmp/nginx.pid; # Changed from /var/run/nginx.pid

    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8080; # Changed from default 80 port
          server_name  _;
          location / {
              root   html;
              index  index.html index.htm;
          }
      }
    }